version: 2

before:
  hooks:
    - go mod tidy

# Build customization
builds:
  - binary: '{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - '386'
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'

# Archive customization
archives:
  - id: terraform-provider
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*  # Only archive the binary
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root

# Checksum generation
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

# Signing configuration
signs:
  - cmd: gpg
    artifacts: checksum
    output: ${signature}
    args: ["--batch", "-u", "{{ .Env.GPG_KEY }}", "--passphrase", "{{ .Env.PASSPHRASE }}", "--pinentry-mode", "loopback", "--output", "${signature}", "--detach-sign", "${artifact}"]

# Release customization
changelog:
  disable: true

# Publisher configuration
release:
  draft: false
  prerelease: auto
  mode: replace

# Validation
builds_info:
  mode: auto
