version: 2

builds:
  - binary: '{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['zip']
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

signs:
  - cmd: gpg
    artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_KEY }}", "--passphrase", "{{ .Env.PASSPHRASE }}", "--detach-sign", "${artifact}"]

changelog:
  disable: true
